### ISSUE TITLE
Mock NATS server implementation in order to be able to write unit tests

### ISSUE THREAD

**Issue by imsazzad** [nats-io/nats.py#160]
Hello, I am new to NATS.io.  I want to write unit test for my subscriber. In order for consumers to be able to write unit tests for their subscription logic, they need a way to publish messages. 

I am looking for a useful doc. could you please guide any?

**Comment by bvanelli** [comment]
I'm not entirely sure but I think they have a fake server for running testes [here](https://github.com/nats-io/nats.py/blob/b77bd2be28296fd4e1db9082f634bb80c7690b29/tests/utils.py#L12). The class you need to extend to run your tests should be [this one](https://github.com/nats-io/nats.py/blob/b77bd2be28296fd4e1db9082f634bb80c7690b29/tests/utils.py#L152-L169).  You can see they using it [to test the subscriptions](https://github.com/nats-io/nats.py/blob/master/tests/client_async_await_test.py#L10-L34).

**Comment by charliestrawn** [comment]
I don't think @bvanelli's comment is what you want. I can see how it looks like we're mocking the server, but that class is actually wrapper that starts a *real* nats-server binary to verify integrations between the client and server work for things like connect, reconnects, and general protocol communication.

Typically in python unit tests you use the [mock library](https://docs.python.org/3/library/unittest.mock.html) to setup expected interactions with dependencies. We have some examples of this in my company's open source library that uses this client. [Here](https://github.com/Workiva/frugal/blob/master/lib/python/frugal/tests/aio/transport/test_nats_transport.py#L28) is where we initialize the mock, and [here](https://github.com/Workiva/frugal/blob/master/lib/python/frugal/tests/aio/transport/test_nats_transport.py#L68-L70) is an example of setting up a return value for the method call.

Closing this issues as stale because it's been a few months, but I wanted to give some examples for posterity. Feel free to follow up with any questions.

**Comment by misuzu** [comment]
Would be awesome to have `NATSD` class included in the main package to be able to write unittests without copy-pasting `tests/utils.py`
