### ISSUE TITLE
How to use JetStream with nats.py ?

### ISSUE THREAD

**Issue by Ro0tk1t** [nats-io/nats.py#200]
i see `nats.go` can use JetStream directly, but `nats.py` does not has JetStream related code and usage instructions.

**Comment by 300LiterPropofol** [comment]
I think Jetstream only supports go client and node client at present, which is understandable considering it is really new. But I also really would like to know whether the NATS team can give us a time plan that when the python client will be released.

**Comment by charbonnierg** [comment]
I wrote a small library on top of `nats.py` which can be use to interact with JetStream. It is not tested and far from complete, but can still be used to perform basic tasks (create stream, read stream info, update stream, delete stream, create consumer, fetch consumer next message, ...) This library was written with a single goal in mind: familiarizing myself with the JetStream API.

Everything is not clear yet, for example, I don't understand how backups should be performed (the same way `nats str backup` performs backup). Fetching the last message from a stream consumer might not be implemented in an optimal way either.
You can find the library and some explanations about it at https://github.com/charbonnierg/jetstream.py 

Two examples notebooks are available:

- [01-streams.ipynb](https://github.com/charbonnierg/jetstream.py/blob/next/examples/01-streams.ipynb)
- [02-consumers.ipynb](https://github.com/charbonnierg/jetstream.py/blob/next/examples/02-consumers.ipynb)

I won't work on this library in order to make it production ready as we're not using JetStream at work yet, but anyone is welcome to fork or send PR

@wallyqs is there any plan to introduce JetStream API client in `nats.py` or this should be done in yet another library ? BTW I don't plan to push the package to `pypi` so the name `jetstream-python` is still available if you plan to provide an official one.

**Comment by wallyqs** [comment]
Hi @charbonnierg you library looks great! The way that you are generating the models looks very useful. I was just adding the helpers to this library on this branch:
https://github.com/nats-io/nats.py/compare/main...js-ctx?expand=1

The way that it will work in this `nats.py` will be similar to Go:

```
import nats

nc = nats.connect()
js = nc.jetstream()
js.publish("foo", b'Hello World')
```

**Comment by charbonnierg** [comment]
@wallyqs do you plan to implement the `Jetstream` class so that each method returns a message (`nats.aio.client.Msg`) or do you intend to return a parsed object such as a dataclass, a pydantic model, or something similar (such as in the library I proposed)?

I think it would be nice if Jetstream API let user work with parsed objects instead of raw NATS messages.

For example in the branch `js-ctx` the `add_consumer` function looks like that:

```python
    async def add_consumer(self, stream_name=None, config={}):
        cfg = {"stream_name": stream_name, "config": config}

        msg = None
        data = json.dumps(cfg)
        if 'durable_name' not in config:
            msg = await self._nc.request(
                f"{self._prefix}.CONSUMER.CREATE.{stream_name}", data.encode()
            )
        else:
            consumer_name = config["durable_name"]
            msg = await self._nc.request(
                f"{self._prefix}.CONSUMER.DURABLE.CREATE.{stream_name}.{consumer_name}",
                data.encode()
            )
        return msg
```

So if I use this method, if I want to access the consumer config, I must do something like:

```python
js = nc.jetstream()
msg = await js.add_consumer(...)
# Parse msg into a dict
response = json.loads(msg.data)
# Access the consumer config
# Note that a KeyError would be raised when response is a JetStream error
config = response["config"]
```

IMHO, it's much simpler to return a parse object:

```python
js = nc.jetstream()
# response is a IoNatsJetstreamApiV1ConsumerCreateResponse
response= await js.add_consumer(...)
# Ideally, a response could be checked for error
# This would raise an error in case response is a JetStream error
response.raise_on_error()
# consumer config can easily be accessed
config = response.config

```

**Comment by wallyqs** [comment]
@charbonnierg agree, handling the parsed objects in the management API as you do looks much cleaner

**Comment by siredmar** [comment]
Will be there any progress in `js-ctx` torwards `main` anytime soon?

**Comment by jgerry2002** [comment]
> @wallyqs will be there any progress in `js-ctx` torwards `main` anytime soon?

I am curious as well. I have a project that I was hoping to test this with.

**Comment by databasedav** [comment]
@siredmar @jgerry2002 fyi, @charbonnierg's https://github.com/charbonnierg/jetstream.py is working great for me while we all wait for support in the official library, i can't imagine the api's will be super different in the end either, so should be quick to switch over

**Comment by jgerry2002** [comment]
> @siredmar @jgerry2002 fyi, @charbonnierg's https://github.com/charbonnierg/jetstream.py is working great for me while we all wait for support in the official library, i can't imagine the api's will be super different in the end either, so should be quick to switch over

I tested @charbonnierg library as well, as my use case is not overly complex. It seems to do the job just fine so far. Hopefully this official project will be updated soon.

**Comment by charbonnierg** [comment]
I opened a PR for both #195  and #200: #210. I hope it can be used as a draft to discuss how JetStream API will be implemented in `nats.py`.

As mentioned in the PR, it's a lot of changes, but if you could take some time to review and suggest how you would have done things @wallyqs it would be great

**Comment by roguh** [comment]
Jetstream support has been added to version 2 in this PR https://github.com/nats-io/nats.py/pull/216

**Comment by Kjir** [comment]
Are queue groups supported already with Jetstream? Or is it something still missing?
In the first case it would be nice to have an example, in the second case is it already in the works?

I am considering suggesting NATS for my current project, but I'm pretty sure we will need queue groups with Jetstream for our use case.

**Comment by wallyqs** [comment]
@Kjir queue groups in JetStream are now supported in v2.0.0rc1 release: https://nats-io.github.io/nats.py/modules.html#nats.js.client.JetStream.subscribe

Doing this would create a consumer with a delivery group named workers for subscribers to receive on the hello subject:

```python
async def main():
    nc = await nats.connect()
    js = nc.jetstream()
    await js.add_stream(name='hello', subjects=['hello'])
    sub = await js.subscribe('hello', 'workers')
```
