### ISSUE TITLE
Non-String Header Values

### ISSUE THREAD

**Issue by DasCapschen** [nats-io/nats.py#286]
Is it possible to implement support for header values that are not strings?

If not, at least updating the Typing, because right now it is `headers: Dict[str, Any]`, but passing anything other than a `Dict[str, str]` will result in an AttributeError, since `_send_publish` calls `v.encode()`.

**Comment by pohlt** [comment]
Because of the protocol NATS is using, I don't think that anything other than string values are possible.

In my application, I put some string values into the header (e.g. message type, timestamp) and any potential binary data goes into the message payload (using msgpack).

You are right about the typing issue.

**Comment by wallyqs** [comment]
It would only support strings, so need to fix the typing issue...

**Comment by wallyqs** [comment]
Fixed via #290
