### ISSUE TITLE
Why is the default behavior of the subscribe method to ignore errors when there is no error_cb defined?

### ISSUE THREAD

**Issue by jccardonar** [nats-io/nats.py#91]
(This was probably discussed before, but I couldn't find where.)

The examples of the library do not force one to use the error cb from day-1. However, without it defined,  errors are silently discarded and there are no signs of them ever happening.

I would prefer for the error to actually be raised. Right, the task will stop, but that is a louder noise than just processing messages as if nothing had happened. It would help if error_cb is always defined in the examples.

We really need #76 for this not to matter, I think.

**Comment by cgebe** [comment]
+1 just wasted an hour since the message_handler was silence on every error.

**Comment by bvanelli** [comment]
Even though I agree (since I've run into similar problems with errors being supressed), it has to be noted that the `error_cb` catches everything, not only problems in the message handling, like connection lost with the server and reconnect atempts, things that the user might want to supress.

I believe errors in the callbacks are supressed to prevent the application from crashing if one subscription has an unexpected problem. Maybe stress on the documentation or replace in the examples:

```python
await nc.connect("demo.nats.io:4222", loop=loop)
```

by something like:

```python
await nc.connect("demo.nats.io:4222", loop=loop, error_cb=print)
```

So that errors actually get printed to the user.
